# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x0freading_example\"$\n\x10getMeDataRequest\x12\x10\n\x08\x63ol_name\x18\x01 \x01(\t\"\x1f\n\x11getMeDataResponse\x12\n\n\x02\x64\x66\x18\x01 \x01(\t2i\n\nComputator\x12[\n\x10getMeInformation\x12!.reading_example.getMeDataRequest\x1a\".reading_example.getMeDataResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETMEDATAREQUEST._serialized_start=34
  _GETMEDATAREQUEST._serialized_end=70
  _GETMEDATARESPONSE._serialized_start=72
  _GETMEDATARESPONSE._serialized_end=103
  _COMPUTATOR._serialized_start=105
  _COMPUTATOR._serialized_end=210
# @@protoc_insertion_point(module_scope)
