# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2


class ComputatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMeInformation = channel.unary_unary(
                '/reading_example.Computator/getMeInformation',
                request_serializer=example__pb2.getMeDataRequest.SerializeToString,
                response_deserializer=example__pb2.getMeDataResponse.FromString,
                )


class ComputatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getMeInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMeInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.getMeInformation,
                    request_deserializer=example__pb2.getMeDataRequest.FromString,
                    response_serializer=example__pb2.getMeDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reading_example.Computator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Computator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getMeInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reading_example.Computator/getMeInformation',
            example__pb2.getMeDataRequest.SerializeToString,
            example__pb2.getMeDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
